### ISSUE TITLE
Release v1.0.0-a

### ISSUE THREAD

**Issue by NPEX42** [RustKernal/tinix-II#1]
----
- [x] - PIC - 0.1.0
- [x] - PIT - 0.2.0
- [x] - Interrupts - 0.3.0 
- [x] - Basic Graphics Library - 0.4.0
- [x]  - GDT Implementation - 0.5.0  - [Issue #2]
- [x] - Triple Fault Protection - 0.6.0 - [Issue #2]
- [x] - Keyboard Input - 0.7.0 - [Issue #3]
- [x] - Memory Allocation - 0.8.0 - [Issue #4]
- [x] - CMOS - 0.9.0 - [Issue #6]
- [x] - RTC - 0.10.0 - [Issue #7]
- [ ] - ATA - 0.11.0 - [Issue #8]
- [ ] - Basic Shell - 0.12.0 - [Issue #9 ]
- [ ] - Simple Program Loader (ELF64) - 0.13.0 - [Issue #10]

**Comment by NPEX42** [comment]
![TinixII_Module_Map](https://user-images.githubusercontent.com/64636838/123868471-a4658280-d927-11eb-86c5-83ec082141e7.png)

**Comment by NPEX42** [comment]
![TinixII_Module_Map](https://user-images.githubusercontent.com/64636838/123868553-c65f0500-d927-11eb-94d3-a1caddf30749.png)
---
A Potential Module Level Architecture for Version 1.0.0a
