### ISSUE TITLE
0.8.0 - Memory Allocation - To-Do

### ISSUE THREAD

**Issue by NPEX42** [RustKernal/tinix-II#4]
- [x] - Add Level 4 Page table interaction
- [x] - Add Frame Mapper
- [x] - Add Frame Allocator
- [x] - Assign Linked list allocator to the global Alloc
